### ISSUE TITLE
.when(empty list) doesn't resolve

### ISSUE THREAD

**Issue by andyrohan** [nascentdigital/standby#1]
If you calling Promise.when() with an empty list the Promise does not resolve.

Would be ideal if the Promise resolved with an empty list so that you dont have to check length of list before calling .when and determining how to handle.

**Comment by twillw** [comment]
Fixed with version 2.0.6: [this commit](https://github.com/nascentdigital/standby/commit/e6de5a5672c01c6b42c99ef0757ba8f283dc6f6f)
